version: "3"

services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped
    environment:
      - APPSMITH_ENCRYPTION_PASSWORD=${APPSMITH_ENCRYPTION_PASSWORD}
      - APPSMITH_ENCRYPTION_SALT=${APPSMITH_ENCRYPTION_SALT}
      - APPSMITH_SUPERVISOR_PASSWORD=${APPSMITH_SUPERVISOR_PASSWORD}
